name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "00 15 * * *"

jobs:
  cabal:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15, windows-2019]
        ghc: ["8.6", "8.8"]
        cabal: ["3.0"]
        cache-version: ["2020-09-22"]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Cache ~/.cabal/store
      uses: actions/cache@v2
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ matrix.cache-version }}-cabal

    - name: Install dependencies
      run: |
        cabal update
        cabal configure --disable-optimization --write-ghc-environment-files=always -j2
        cabal build --only-dependencies

    - name: Build
      run: cabal build